//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Backup) DeepCopyInto(out *Backup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backup.
func (in *Backup) DeepCopy() *Backup {
	if in == nil {
		return nil
	}
	out := new(Backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Backup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupList) DeepCopyInto(out *BackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Backup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupList.
func (in *BackupList) DeepCopy() *BackupList {
	if in == nil {
		return nil
	}
	out := new(BackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPlan) DeepCopyInto(out *BackupPlan) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	out.SourcePV = in.SourcePV
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPlan.
func (in *BackupPlan) DeepCopy() *BackupPlan {
	if in == nil {
		return nil
	}
	out := new(BackupPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepository) DeepCopyInto(out *BackupRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepository.
func (in *BackupRepository) DeepCopy() *BackupRepository {
	if in == nil {
		return nil
	}
	out := new(BackupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryBindingStatus) DeepCopyInto(out *BackupRepositoryBindingStatus) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3BackupRepositoryBindingStatus)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCBackupRepositoryBindingStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryBindingStatus.
func (in *BackupRepositoryBindingStatus) DeepCopy() *BackupRepositoryBindingStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryList) DeepCopyInto(out *BackupRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryList.
func (in *BackupRepositoryList) DeepCopy() *BackupRepositoryList {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositorySecretReference) DeepCopyInto(out *BackupRepositorySecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositorySecretReference.
func (in *BackupRepositorySecretReference) DeepCopy() *BackupRepositorySecretReference {
	if in == nil {
		return nil
	}
	out := new(BackupRepositorySecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositorySpec) DeepCopyInto(out *BackupRepositorySpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3BackupRepositorySpec)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCBackupRepositorySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositorySpec.
func (in *BackupRepositorySpec) DeepCopy() *BackupRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(BackupRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	if in.SourcePV != nil {
		in, out := &in.SourcePV, &out.SourcePV
		*out = new(LocalResourceReference)
		**out = **in
	}
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(BackupPlan)
		**out = **in
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(BackupRepositoryBindingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenEBSLVMSharedMounts != nil {
		in, out := &in.OpenEBSLVMSharedMounts, &out.OpenEBSLVMSharedMounts
		*out = make([]SharedMountStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopy) DeepCopyInto(out *ClusterCopy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopy.
func (in *ClusterCopy) DeepCopy() *ClusterCopy {
	if in == nil {
		return nil
	}
	out := new(ClusterCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCopy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopyList) DeepCopyInto(out *ClusterCopyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopyList.
func (in *ClusterCopyList) DeepCopy() *ClusterCopyList {
	if in == nil {
		return nil
	}
	out := new(ClusterCopyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCopyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopyPlan) DeepCopyInto(out *ClusterCopyPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopyPlan.
func (in *ClusterCopyPlan) DeepCopy() *ClusterCopyPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterCopyPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopySpec) DeepCopyInto(out *ClusterCopySpec) {
	*out = *in
	in.CopySpec.DeepCopyInto(&out.CopySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopySpec.
func (in *ClusterCopySpec) DeepCopy() *ClusterCopySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCopySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopyStatus) DeepCopyInto(out *ClusterCopyStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ClusterCopyPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterCopyVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopyStatus.
func (in *ClusterCopyStatus) DeepCopy() *ClusterCopyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCopyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCopyVolumeStatus) DeepCopyInto(out *ClusterCopyVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = (*in).DeepCopy()
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = (*in).DeepCopy()
	}
	in.Sync.DeepCopyInto(&out.Sync)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCopyVolumeStatus.
func (in *ClusterCopyVolumeStatus) DeepCopy() *ClusterCopyVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCopyVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigration) DeepCopyInto(out *ClusterMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigration.
func (in *ClusterMigration) DeepCopy() *ClusterMigration {
	if in == nil {
		return nil
	}
	out := new(ClusterMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationList) DeepCopyInto(out *ClusterMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationList.
func (in *ClusterMigrationList) DeepCopy() *ClusterMigrationList {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationPlan) DeepCopyInto(out *ClusterMigrationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationPlan.
func (in *ClusterMigrationPlan) DeepCopy() *ClusterMigrationPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationSpec) DeepCopyInto(out *ClusterMigrationSpec) {
	*out = *in
	in.MigrationSpec.DeepCopyInto(&out.MigrationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationSpec.
func (in *ClusterMigrationSpec) DeepCopy() *ClusterMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationStatus) DeepCopyInto(out *ClusterMigrationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ClusterMigrationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterMigrationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationStatus.
func (in *ClusterMigrationStatus) DeepCopy() *ClusterMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationVolumeStatus) DeepCopyInto(out *ClusterMigrationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = (*in).DeepCopy()
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = (*in).DeepCopy()
	}
	in.Sync.DeepCopyInto(&out.Sync)
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationVolumeStatus.
func (in *ClusterMigrationVolumeStatus) DeepCopy() *ClusterMigrationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigration) DeepCopyInto(out *ClusterPodMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigration.
func (in *ClusterPodMigration) DeepCopy() *ClusterPodMigration {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationList) DeepCopyInto(out *ClusterPodMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPodMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationList.
func (in *ClusterPodMigrationList) DeepCopy() *ClusterPodMigrationList {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPodMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationPlan) DeepCopyInto(out *ClusterPodMigrationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationPlan.
func (in *ClusterPodMigrationPlan) DeepCopy() *ClusterPodMigrationPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationSpec) DeepCopyInto(out *ClusterPodMigrationSpec) {
	*out = *in
	in.PodMigrationSpec.DeepCopyInto(&out.PodMigrationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationSpec.
func (in *ClusterPodMigrationSpec) DeepCopy() *ClusterPodMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationStatus) DeepCopyInto(out *ClusterPodMigrationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ClusterPodMigrationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(ClusterPodMigrationWorkloadStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterPodMigrationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OpenEBSLVMSharedMounts != nil {
		in, out := &in.OpenEBSLVMSharedMounts, &out.OpenEBSLVMSharedMounts
		*out = make([]ClusterSharedMountStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationStatus.
func (in *ClusterPodMigrationStatus) DeepCopy() *ClusterPodMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationVolumeStatus) DeepCopyInto(out *ClusterPodMigrationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = (*in).DeepCopy()
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = (*in).DeepCopy()
	}
	in.Sync.DeepCopyInto(&out.Sync)
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationVolumeStatus.
func (in *ClusterPodMigrationVolumeStatus) DeepCopy() *ClusterPodMigrationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodMigrationWorkloadStatus) DeepCopyInto(out *ClusterPodMigrationWorkloadStatus) {
	*out = *in
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = (*in).DeepCopy()
	}
	if in.AffectedPods != nil {
		in, out := &in.AffectedPods, &out.AffectedPods
		*out = make([]ObjectReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodMigrationWorkloadStatus.
func (in *ClusterPodMigrationWorkloadStatus) DeepCopy() *ClusterPodMigrationWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPodMigrationWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservation) DeepCopyInto(out *ClusterReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservation.
func (in *ClusterReservation) DeepCopy() *ClusterReservation {
	if in == nil {
		return nil
	}
	out := new(ClusterReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservationList) DeepCopyInto(out *ClusterReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservationList.
func (in *ClusterReservationList) DeepCopy() *ClusterReservationList {
	if in == nil {
		return nil
	}
	out := new(ClusterReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservationPlan) DeepCopyInto(out *ClusterReservationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservationPlan.
func (in *ClusterReservationPlan) DeepCopy() *ClusterReservationPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterReservationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservationSpec) DeepCopyInto(out *ClusterReservationSpec) {
	*out = *in
	in.ReservationSpec.DeepCopyInto(&out.ReservationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservationSpec.
func (in *ClusterReservationSpec) DeepCopy() *ClusterReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservationStatus) DeepCopyInto(out *ClusterReservationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ClusterReservationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ClusterReservationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservationStatus.
func (in *ClusterReservationStatus) DeepCopy() *ClusterReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReservationVolumeStatus) DeepCopyInto(out *ClusterReservationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = (*in).DeepCopy()
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReservationVolumeStatus.
func (in *ClusterReservationVolumeStatus) DeepCopy() *ClusterReservationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterReservationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSharedMountStatus) DeepCopyInto(out *ClusterSharedMountStatus) {
	*out = *in
	out.SourcePV = in.SourcePV
	in.LVMVolume.DeepCopyInto(&out.LVMVolume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSharedMountStatus.
func (in *ClusterSharedMountStatus) DeepCopy() *ClusterSharedMountStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSharedMountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVolumeActivationStatus) DeepCopyInto(out *ClusterVolumeActivationStatus) {
	*out = *in
	if in.ActivePVC != nil {
		in, out := &in.ActivePVC, &out.ActivePVC
		*out = (*in).DeepCopy()
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RolledBackAt != nil {
		in, out := &in.RolledBackAt, &out.RolledBackAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVolumeActivationStatus.
func (in *ClusterVolumeActivationStatus) DeepCopy() *ClusterVolumeActivationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterVolumeActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVolumeSpec) DeepCopyInto(out *ClusterVolumeSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	out.SourcePV = in.SourcePV
	out.DestinationPVC = in.DestinationPVC
	in.SourcePVCSpec.DeepCopyInto(&out.SourcePVCSpec)
	in.SourcePVCMetadata.DeepCopyInto(&out.SourcePVCMetadata)
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.TransferScope != nil {
		in, out := &in.TransferScope, &out.TransferScope
		*out = new(TransferScope)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVolumeSpec.
func (in *ClusterVolumeSpec) DeepCopy() *ClusterVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterWorkloadSpec) DeepCopyInto(out *ClusterWorkloadSpec) {
	*out = *in
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Ordinal != nil {
		in, out := &in.Ordinal, &out.Ordinal
		*out = new(int32)
		**out = **in
	}
	if in.AffectedPods != nil {
		in, out := &in.AffectedPods, &out.AffectedPods
		*out = make([]LocalResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.OriginalObject != nil {
		in, out := &in.OriginalObject, &out.OriginalObject
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeBlocks != nil {
		in, out := &in.KubeBlocks, &out.KubeBlocks
		*out = new(KubeBlocksSpec)
		**out = **in
	}
	if in.VMCluster != nil {
		in, out := &in.VMCluster, &out.VMCluster
		*out = new(VMClusterSpec)
		**out = **in
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterWorkloadSpec.
func (in *ClusterWorkloadSpec) DeepCopy() *ClusterWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Copy) DeepCopyInto(out *Copy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Copy.
func (in *Copy) DeepCopy() *Copy {
	if in == nil {
		return nil
	}
	out := new(Copy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Copy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyList) DeepCopyInto(out *CopyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Copy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyList.
func (in *CopyList) DeepCopy() *CopyList {
	if in == nil {
		return nil
	}
	out := new(CopyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CopyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyPlan) DeepCopyInto(out *CopyPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyPlan.
func (in *CopyPlan) DeepCopy() *CopyPlan {
	if in == nil {
		return nil
	}
	out := new(CopyPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopySpec) DeepCopyInto(out *CopySpec) {
	*out = *in
	in.TransferOptions.DeepCopyInto(&out.TransferOptions)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LocalResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopySpec.
func (in *CopySpec) DeepCopy() *CopySpec {
	if in == nil {
		return nil
	}
	out := new(CopySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyStatus) DeepCopyInto(out *CopyStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(CopyPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]CopyVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyStatus.
func (in *CopyStatus) DeepCopy() *CopyStatus {
	if in == nil {
		return nil
	}
	out := new(CopyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopySyncStatus) DeepCopyInto(out *CopySyncStatus) {
	*out = *in
	if in.WarmCompletedAt != nil {
		in, out := &in.WarmCompletedAt, &out.WarmCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopySyncStatus.
func (in *CopySyncStatus) DeepCopy() *CopySyncStatus {
	if in == nil {
		return nil
	}
	out := new(CopySyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyVolumeStatus) DeepCopyInto(out *CopyVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = new(LocalResourceReference)
		**out = **in
	}
	in.Sync.DeepCopyInto(&out.Sync)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyVolumeStatus.
func (in *CopyVolumeStatus) DeepCopy() *CopyVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(CopyVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaSpec) DeepCopyInto(out *GrafanaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSpec.
func (in *GrafanaSpec) DeepCopy() *GrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeBlocksSpec) DeepCopyInto(out *KubeBlocksSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeBlocksSpec.
func (in *KubeBlocksSpec) DeepCopy() *KubeBlocksSpec {
	if in == nil {
		return nil
	}
	out := new(KubeBlocksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResourceReference) DeepCopyInto(out *LocalResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResourceReference.
func (in *LocalResourceReference) DeepCopy() *LocalResourceReference {
	if in == nil {
		return nil
	}
	out := new(LocalResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Migration) DeepCopyInto(out *Migration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Migration.
func (in *Migration) DeepCopy() *Migration {
	if in == nil {
		return nil
	}
	out := new(Migration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Migration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationList) DeepCopyInto(out *MigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Migration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationList.
func (in *MigrationList) DeepCopy() *MigrationList {
	if in == nil {
		return nil
	}
	out := new(MigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlan) DeepCopyInto(out *MigrationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlan.
func (in *MigrationPlan) DeepCopy() *MigrationPlan {
	if in == nil {
		return nil
	}
	out := new(MigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
	in.TransferOptions.DeepCopyInto(&out.TransferOptions)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationStatus) DeepCopyInto(out *MigrationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(MigrationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]MigrationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationStatus.
func (in *MigrationStatus) DeepCopy() *MigrationStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSyncStatus) DeepCopyInto(out *MigrationSyncStatus) {
	*out = *in
	if in.FinalCompletedAt != nil {
		in, out := &in.FinalCompletedAt, &out.FinalCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSyncStatus.
func (in *MigrationSyncStatus) DeepCopy() *MigrationSyncStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationVolumeStatus) DeepCopyInto(out *MigrationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = new(LocalResourceReference)
		**out = **in
	}
	in.Sync.DeepCopyInto(&out.Sync)
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationVolumeStatus.
func (in *MigrationVolumeStatus) DeepCopy() *MigrationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Move) DeepCopyInto(out *Move) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Move.
func (in *Move) DeepCopy() *Move {
	if in == nil {
		return nil
	}
	out := new(Move)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Move) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveActivationStatus) DeepCopyInto(out *MoveActivationStatus) {
	*out = *in
	if in.ActivePVC != nil {
		in, out := &in.ActivePVC, &out.ActivePVC
		*out = (*in).DeepCopy()
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RolledBackAt != nil {
		in, out := &in.RolledBackAt, &out.RolledBackAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveActivationStatus.
func (in *MoveActivationStatus) DeepCopy() *MoveActivationStatus {
	if in == nil {
		return nil
	}
	out := new(MoveActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveIdentity) DeepCopyInto(out *MoveIdentity) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	out.SourcePV = in.SourcePV
	out.DestinationPVC = in.DestinationPVC
	in.SourceTemplate.DeepCopyInto(&out.SourceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveIdentity.
func (in *MoveIdentity) DeepCopy() *MoveIdentity {
	if in == nil {
		return nil
	}
	out := new(MoveIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveList) DeepCopyInto(out *MoveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Move, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveList.
func (in *MoveList) DeepCopy() *MoveList {
	if in == nil {
		return nil
	}
	out := new(MoveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MovePlan) DeepCopyInto(out *MovePlan) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MovePlan.
func (in *MovePlan) DeepCopy() *MovePlan {
	if in == nil {
		return nil
	}
	out := new(MovePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveSpec) DeepCopyInto(out *MoveSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	if in.SourcePV != nil {
		in, out := &in.SourcePV, &out.SourcePV
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveSpec.
func (in *MoveSpec) DeepCopy() *MoveSpec {
	if in == nil {
		return nil
	}
	out := new(MoveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveStatus) DeepCopyInto(out *MoveStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(MovePlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]MoveVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveStatus.
func (in *MoveStatus) DeepCopy() *MoveStatus {
	if in == nil {
		return nil
	}
	out := new(MoveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveVolumeStatus) DeepCopyInto(out *MoveVolumeStatus) {
	*out = *in
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveVolumeStatus.
func (in *MoveVolumeStatus) DeepCopy() *MoveVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(MoveVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCBackupRepositoryBindingStatus) DeepCopyInto(out *PVCBackupRepositoryBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCBackupRepositoryBindingStatus.
func (in *PVCBackupRepositoryBindingStatus) DeepCopy() *PVCBackupRepositoryBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PVCBackupRepositoryBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCBackupRepositorySpec) DeepCopyInto(out *PVCBackupRepositorySpec) {
	*out = *in
	out.ClaimRef = in.ClaimRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCBackupRepositorySpec.
func (in *PVCBackupRepositorySpec) DeepCopy() *PVCBackupRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(PVCBackupRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCIdentityActivationStatus) DeepCopyInto(out *PVCIdentityActivationStatus) {
	*out = *in
	if in.ActivePVC != nil {
		in, out := &in.ActivePVC, &out.ActivePVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RolledBackAt != nil {
		in, out := &in.RolledBackAt, &out.RolledBackAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCIdentityActivationStatus.
func (in *PVCIdentityActivationStatus) DeepCopy() *PVCIdentityActivationStatus {
	if in == nil {
		return nil
	}
	out := new(PVCIdentityActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCIdentityFields) DeepCopyInto(out *PVCIdentityFields) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	out.SourcePV = in.SourcePV
	out.DestinationPVC = in.DestinationPVC
	in.SourceTemplate.DeepCopyInto(&out.SourceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCIdentityFields.
func (in *PVCIdentityFields) DeepCopy() *PVCIdentityFields {
	if in == nil {
		return nil
	}
	out := new(PVCIdentityFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCIdentityVolumeStatus) DeepCopyInto(out *PVCIdentityVolumeStatus) {
	*out = *in
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCIdentityVolumeStatus.
func (in *PVCIdentityVolumeStatus) DeepCopy() *PVCIdentityVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(PVCIdentityVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCMetadata) DeepCopyInto(out *PVCMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OwnerReferences != nil {
		in, out := &in.OwnerReferences, &out.OwnerReferences
		*out = make([]metav1.OwnerReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCMetadata.
func (in *PVCMetadata) DeepCopy() *PVCMetadata {
	if in == nil {
		return nil
	}
	out := new(PVCMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSourceTemplate) DeepCopyInto(out *PVCSourceTemplate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Metadata.DeepCopyInto(&out.Metadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSourceTemplate.
func (in *PVCSourceTemplate) DeepCopy() *PVCSourceTemplate {
	if in == nil {
		return nil
	}
	out := new(PVCSourceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigration) DeepCopyInto(out *PodMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigration.
func (in *PodMigration) DeepCopy() *PodMigration {
	if in == nil {
		return nil
	}
	out := new(PodMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationList) DeepCopyInto(out *PodMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationList.
func (in *PodMigrationList) DeepCopy() *PodMigrationList {
	if in == nil {
		return nil
	}
	out := new(PodMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationPlan) DeepCopyInto(out *PodMigrationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationPlan.
func (in *PodMigrationPlan) DeepCopy() *PodMigrationPlan {
	if in == nil {
		return nil
	}
	out := new(PodMigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationSpec) DeepCopyInto(out *PodMigrationSpec) {
	*out = *in
	in.TransferOptions.DeepCopyInto(&out.TransferOptions)
	out.Pod = in.Pod
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationSpec.
func (in *PodMigrationSpec) DeepCopy() *PodMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(PodMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationStatus) DeepCopyInto(out *PodMigrationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(PodMigrationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(PodMigrationWorkloadStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]PodMigrationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OpenEBSLVMSharedMounts != nil {
		in, out := &in.OpenEBSLVMSharedMounts, &out.OpenEBSLVMSharedMounts
		*out = make([]SharedMountStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationStatus.
func (in *PodMigrationStatus) DeepCopy() *PodMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(PodMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationSyncStatus) DeepCopyInto(out *PodMigrationSyncStatus) {
	*out = *in
	if in.WarmCompletedAt != nil {
		in, out := &in.WarmCompletedAt, &out.WarmCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FinalCompletedAt != nil {
		in, out := &in.FinalCompletedAt, &out.FinalCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationSyncStatus.
func (in *PodMigrationSyncStatus) DeepCopy() *PodMigrationSyncStatus {
	if in == nil {
		return nil
	}
	out := new(PodMigrationSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationVolumeStatus) DeepCopyInto(out *PodMigrationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = new(LocalResourceReference)
		**out = **in
	}
	in.Sync.DeepCopyInto(&out.Sync)
	in.Activation.DeepCopyInto(&out.Activation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationVolumeStatus.
func (in *PodMigrationVolumeStatus) DeepCopy() *PodMigrationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(PodMigrationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationWorkloadStatus) DeepCopyInto(out *PodMigrationWorkloadStatus) {
	*out = *in
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.AffectedPods != nil {
		in, out := &in.AffectedPods, &out.AffectedPods
		*out = make([]LocalResourceReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationWorkloadStatus.
func (in *PodMigrationWorkloadStatus) DeepCopy() *PodMigrationWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(PodMigrationWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rename) DeepCopyInto(out *Rename) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rename.
func (in *Rename) DeepCopy() *Rename {
	if in == nil {
		return nil
	}
	out := new(Rename)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rename) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameList) DeepCopyInto(out *RenameList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rename, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameList.
func (in *RenameList) DeepCopy() *RenameList {
	if in == nil {
		return nil
	}
	out := new(RenameList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RenameList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenamePlan) DeepCopyInto(out *RenamePlan) {
	*out = *in
	in.PVCIdentityFields.DeepCopyInto(&out.PVCIdentityFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenamePlan.
func (in *RenamePlan) DeepCopy() *RenamePlan {
	if in == nil {
		return nil
	}
	out := new(RenamePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameSpec) DeepCopyInto(out *RenameSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	if in.SourcePV != nil {
		in, out := &in.SourcePV, &out.SourcePV
		*out = new(LocalResourceReference)
		**out = **in
	}
	out.DestinationPVC = in.DestinationPVC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameSpec.
func (in *RenameSpec) DeepCopy() *RenameSpec {
	if in == nil {
		return nil
	}
	out := new(RenameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameStatus) DeepCopyInto(out *RenameStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(RenamePlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]PVCIdentityVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameStatus.
func (in *RenameStatus) DeepCopy() *RenameStatus {
	if in == nil {
		return nil
	}
	out := new(RenameStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Reservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationList) DeepCopyInto(out *ReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationList.
func (in *ReservationList) DeepCopy() *ReservationList {
	if in == nil {
		return nil
	}
	out := new(ReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationPlan) DeepCopyInto(out *ReservationPlan) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationPlan.
func (in *ReservationPlan) DeepCopy() *ReservationPlan {
	if in == nil {
		return nil
	}
	out := new(ReservationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSpec) DeepCopyInto(out *ReservationSpec) {
	*out = *in
	in.TransferOptions.DeepCopyInto(&out.TransferOptions)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LocalResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSpec.
func (in *ReservationSpec) DeepCopy() *ReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationStatus) DeepCopyInto(out *ReservationStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ReservationPlan)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ReservationVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationStatus.
func (in *ReservationStatus) DeepCopy() *ReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationVolumeStatus) DeepCopyInto(out *ReservationVolumeStatus) {
	*out = *in
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = new(LocalResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationVolumeStatus.
func (in *ReservationVolumeStatus) DeepCopy() *ReservationVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ReservationVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Restore) DeepCopyInto(out *Restore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Restore.
func (in *Restore) DeepCopy() *Restore {
	if in == nil {
		return nil
	}
	out := new(Restore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Restore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreList) DeepCopyInto(out *RestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Restore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreList.
func (in *RestoreList) DeepCopy() *RestoreList {
	if in == nil {
		return nil
	}
	out := new(RestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePlan) DeepCopyInto(out *RestorePlan) {
	*out = *in
	out.DestinationPVC = in.DestinationPVC
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePlan.
func (in *RestorePlan) DeepCopy() *RestorePlan {
	if in == nil {
		return nil
	}
	out := new(RestorePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSpec) DeepCopyInto(out *RestoreSpec) {
	*out = *in
	out.DestinationPVC = in.DestinationPVC
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSpec.
func (in *RestoreSpec) DeepCopy() *RestoreSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(RestorePlan)
		**out = **in
	}
	in.WorkflowStatus.DeepCopyInto(&out.WorkflowStatus)
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(BackupRepositoryBindingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = (*in).DeepCopy()
	}
	if in.DestinationPV != nil {
		in, out := &in.DestinationPV, &out.DestinationPV
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackupRepositoryBindingStatus) DeepCopyInto(out *S3BackupRepositoryBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackupRepositoryBindingStatus.
func (in *S3BackupRepositoryBindingStatus) DeepCopy() *S3BackupRepositoryBindingStatus {
	if in == nil {
		return nil
	}
	out := new(S3BackupRepositoryBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackupRepositorySpec) DeepCopyInto(out *S3BackupRepositorySpec) {
	*out = *in
	out.CredentialsSecret = in.CredentialsSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackupRepositorySpec.
func (in *S3BackupRepositorySpec) DeepCopy() *S3BackupRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(S3BackupRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMountStatus) DeepCopyInto(out *SharedMountStatus) {
	*out = *in
	out.SourcePV = in.SourcePV
	out.LVMVolume = in.LVMVolume
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMountStatus.
func (in *SharedMountStatus) DeepCopy() *SharedMountStatus {
	if in == nil {
		return nil
	}
	out := new(SharedMountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOptions) DeepCopyInto(out *TransferOptions) {
	*out = *in
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOptions.
func (in *TransferOptions) DeepCopy() *TransferOptions {
	if in == nil {
		return nil
	}
	out := new(TransferOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferScope) DeepCopyInto(out *TransferScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferScope.
func (in *TransferScope) DeepCopy() *TransferScope {
	if in == nil {
		return nil
	}
	out := new(TransferScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMClusterSpec) DeepCopyInto(out *VMClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMClusterSpec.
func (in *VMClusterSpec) DeepCopy() *VMClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VMClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeActivationStatus) DeepCopyInto(out *VolumeActivationStatus) {
	*out = *in
	if in.ActivePVC != nil {
		in, out := &in.ActivePVC, &out.ActivePVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RolledBackAt != nil {
		in, out := &in.RolledBackAt, &out.RolledBackAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeActivationStatus.
func (in *VolumeActivationStatus) DeepCopy() *VolumeActivationStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRequest) DeepCopyInto(out *VolumeRequest) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	if in.SourcePV != nil {
		in, out := &in.SourcePV, &out.SourcePV
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.DestinationPVC != nil {
		in, out := &in.DestinationPVC, &out.DestinationPVC
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.TransferScope != nil {
		in, out := &in.TransferScope, &out.TransferScope
		*out = new(TransferScope)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRequest.
func (in *VolumeRequest) DeepCopy() *VolumeRequest {
	if in == nil {
		return nil
	}
	out := new(VolumeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	out.SourcePV = in.SourcePV
	out.DestinationPVC = in.DestinationPVC
	in.SourcePVCSpec.DeepCopyInto(&out.SourcePVCSpec)
	in.SourcePVCMetadata.DeepCopyInto(&out.SourcePVCMetadata)
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.TransferScope != nil {
		in, out := &in.TransferScope, &out.TransferScope
		*out = new(TransferScope)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowCondition) DeepCopyInto(out *WorkflowCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowCondition.
func (in *WorkflowCondition) DeepCopy() *WorkflowCondition {
	if in == nil {
		return nil
	}
	out := new(WorkflowCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowHistoryEntry) DeepCopyInto(out *WorkflowHistoryEntry) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowHistoryEntry.
func (in *WorkflowHistoryEntry) DeepCopy() *WorkflowHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(WorkflowHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStatus) DeepCopyInto(out *WorkflowStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WorkflowCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]WorkflowHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStatus.
func (in *WorkflowStatus) DeepCopy() *WorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(WorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(LocalResourceReference)
		**out = **in
	}
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Ordinal != nil {
		in, out := &in.Ordinal, &out.Ordinal
		*out = new(int32)
		**out = **in
	}
	if in.AffectedPods != nil {
		in, out := &in.AffectedPods, &out.AffectedPods
		*out = make([]LocalResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.OriginalObject != nil {
		in, out := &in.OriginalObject, &out.OriginalObject
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeBlocks != nil {
		in, out := &in.KubeBlocks, &out.KubeBlocks
		*out = new(KubeBlocksSpec)
		**out = **in
	}
	if in.VMCluster != nil {
		in, out := &in.VMCluster, &out.VMCluster
		*out = new(VMClusterSpec)
		**out = **in
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
